ALTER TABLE JOB ADD CONSTRAINT PK_JOB PRIMARY KEY(JOB_ID)
DESC JOB
ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_EMP FOREIGN KEY(JOB_ID) REFERENCES JOB(JOB_ID)
CREATE TABLE LOCK1
(
STUDENT_ID VARCHAR2(20),
STUDENT_NAME VARCHAR2(20),
BRANCH VARCHAR2(10),
DIVISION NUMBER(10),
PRIMARY KEY(STUDENT_ID)
);
ALTER TABLE JOB DROP CONSTRAINT PK_JOB 
ALTER TABLE EMPLOYEE DROP CONSTRAINT FK_EMP